### ISSUE TITLE
Security names are unclean

### ISSUE THREAD

**Issue by pfalcon** [portfolio-report/pr-www#461]
It's pretty nice idea to have a datasource for Portfolio Performance which can supply ISIN, etc. Thanks for you effort! However, the main information piece provided by Portfolio Report - the security name - leaves much to be desired. Let's have a look for example at https://www.portfolio-report.net/securities/96d13e17cb3b4ff68ff8c181db382c53 ,  which shows us "PAYPAL HDGS INC.DL-,0001" . Issues are:

* SHOUTING AT USER'S FACE WITH ALL CAPS
* Has questionable abbreviations like "HDGS"
* Has random character noise at the end like "DL-,0001". (Ok, it's probably not character noise, but very, very important information. But given that no mere user knows what it means, and it's misplaced in security name, it's character noise.)

Compare that with Yahoo Finance for example: https://finance.yahoo.com/quote/PYPL "PayPal Holdings, Inc." Nice, clean, and welcoming.

The end result of that is that if someone pulled a bunch of securities from Portfolio Report, their portfolio in Portfolio Performance looks rather unclean, broken-windows like. It's pretty sad again that such a great tool like Portfolio Report falls short on such a last mile. Hopefully that could be fixed.

**Comment by tfabritius** [comment]
Thanks for your feedback. Currently, Portfolio Report contains (only) the name of the security as it is listed on the stock exchange. With the limitations you mentioned.
Possible solutions are:

- Users can rename the securities in Portfolio Performance locally, according to their preferences.
- All securities in Portfolio Report could be renamed centrally
  - manually (depends on people volunteering)
  - using an API (if you know of a free/affordable API, please let me know)

It's a valid idea for improvement but not a bug. This issue tracker is for bugs only. Please use https://forum.portfolio-performance.info to continue the discussion.

**Comment by pfalcon** [comment]
Thanks for the response.

> Currently, Portfolio Report contains (only) the name of the security as it is listed on the stock exchange.

Can you elaborate what's that "the stock exchange"? Given the PYPL example above, my understanding is that its primary listing exchange is NASDAQ and that gives: https://www.nasdaq.com/market-activity/stocks/pypl "PayPal Holdings, Inc. Common Stock (PYPL)". Even nicely cased. https://www.nyse.com/quote/PYPL indeed goes all-caps "PAYPAL HOLDINGS INC PYPL". Still no additional "character noise".

> (if you know of a free/affordable API, please let me know)

My language of choice is Python, and browsing thru the project here on github, I got the impression is that the "default choice" is https://github.com/ranaroussi/yfinance library which gets Yahoo Finance data.

> Please use https://forum.portfolio-performance.info/ to continue the discussion.

Here's another piece of feedback: it's unclear how Portfolio Performance's forum related to Portfolio Report's discussion. If there's a specific section on the forum for discussing Portfolio Report, I'd recommend linking to it directly.

Thanks again.
